name: backend deploy

on:
  pull_request:
    branches: [ prod ]
    
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: recursive
      - name: Copy Code to Remote Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REMOTE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }}:/home/ubuntu/remind-map-backend
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          script: | # 실행할 스크립트
            cd remind-map-backend
            ./gradlew clean build
            cd build/libs/
            chmod +x remindmap-0.0.1-SNAPSHOT.jar
            cd /home/ubuntu
            docker-compose down
            docker rm $(docker ps -aq)
            docker rmi -f $(docker images -q)
            docker builder prune -a --force
            docker-compose up -d
            
            
           
            
